import re, json, ast

def extract_keys_from_translations(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find the en: { ... } block - it's the first one after 'en:'
    # Use a simple approach: extract what's between 'en: {' and the matching close brace
    
    # Actually, let's use a simpler approach - just find all the string patterns in nested structure
    
    defined_keys = set()
    
    # Parse the JS object (simplified approach - look for patterns like key: 'value' or key: {)
    lines = content.split('\n')
    stack = [""]  # current path segments
    
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('//') or stripped.startswith('const') or stripped == 'export default translations;' or stripped.startswith('en:') or stripped.startswith('ar:') or stripped.startswith('})') or stripped.startswith('};') or stripped.startswith('},'):
            continue
        
        # Check if line has a key: value or key: {
        # Pattern: keyName: 'value' or keyName: {
        match = re.match(r'(\s*)(\w+):\s*(.+)$', line)
        if match:
            indent = len(match.group(1))
            key = match.group(2)
            value_part = match.group(3)
            
            # Skip the top-level 'en' and 'ar' keys
            # Adjust stack based on indent
            pass
            
    # Better approach: use the known structure from the file
    return set()

# Actually let me just hardcode the known structure from the file
# and compare with used keys

used_keys_raw = r"""
admin.actions
admin.activeNegotiations
admin.activeProducts
admin.completedOrders
admin.confirmDelete
admin.dashboard
admin.delete
admin.farmers
admin.negotiations
admin.noData
admin.orders
admin.pendingOrders
admin.products
admin.recentOrders
admin.recentUsers
admin.role
admin.search
admin.status
admin.totalProducts
admin.totalUsers
admin.traders
admin.unreadMessages
admin.users
admin.view
auth.buyProducts
auth.createAccount
auth.createAccountBtn
auth.createOne
auth.creatingAccount
auth.email
auth.emailPlaceholder
auth.enterEmailPassword
auth.farmer
auth.fillAllFields
auth.fullName
auth.haveAccount
auth.iAm
auth.invalidEmailPassword
auth.invalidResponse
auth.joinCommunity
auth.login
auth.name
auth.namePlaceholder
auth.noAccount
auth.password
auth.passwordLengthError
auth.passwordMinLength
auth.passwordPlaceholder
auth.registrationFailed
auth.sellProducts
auth.signInSubtitle
auth.signingIn
auth.trader
auth.welcomeBack
bananaClassifier.analyzeRipeness
bananaClassifier.analyzing
bananaClassifier.classifyAnother
bananaClassifier.confAbbr
bananaClassifier.confidence
bananaClassifier.dragDrop
bananaClassifier.dropHere
bananaClassifier.failedClassify
bananaClassifier.gradeA
bananaClassifier.gradeC
bananaClassifier.overallGrade
bananaClassifier.predictionResult
bananaClassifier.recentScans
bananaClassifier.removeImage
bananaClassifier.subtitle
bananaClassifier.supports
bananaClassifier.title
bananaClassifier.topPredictions
common.active
common.all
common.back
common.cancel
common.closed
common.messages
common.orders
common.view
common.waiting
common.yourTurn
conversation
farmer.activeListings
farmer.addNewProduct
farmer.addProduct
farmer.adding
farmer.category
farmer.createError
farmer.deleteConfirm
farmer.deleteFailed
farmer.description
farmer.descriptionPlaceholder
farmer.failedLoad
farmer.fillRequired
farmer.manageListings
farmer.myProducts
farmer.noProducts
farmer.noProductsDesc
farmer.pricePerUnitEGP
farmer.pricePlaceholder
farmer.priceQuantityPositive
farmer.productCount
farmer.productCountPlural
farmer.productTitle
farmer.quantity
farmer.quantityPlaceholder
farmer.selectCategory
farmer.titlePlaceholder
farmer.totalProducts
farmer.totalQuantity
farmer.totalValue
farmer.unit
farmer.units
farmer.yourListings
home.connectingFarmers
home.description
home.goToDashboard
home.heroDirect
home.heroFresh
home.howItWorks
home.marketplaceTagline
messages.failedSend
messages.justNow
messages.messages
messages.noConversations
messages.noMessagesYet
messages.re
messages.search
messages.selectConversation
messages.selectConversationDesc
messages.startConversation
messages.typeMessage
messages.unread
modals.negotiatePrice.available
modals.negotiatePrice.belowAsking
modals.negotiatePrice.current
modals.negotiatePrice.failedSend
modals.negotiatePrice.message
modals.negotiatePrice.messagePlaceholder
modals.negotiatePrice.originalTotal
modals.negotiatePrice.quantity
modals.negotiatePrice.quantityRange
modals.negotiatePrice.sendOffer
modals.negotiatePrice.sending
modals.negotiatePrice.title
modals.negotiatePrice.validPrice
modals.negotiatePrice.yourOffer
modals.negotiatePrice.yourOfferLabel
modals.negotiatePrice.yourSavings
modals.placeOrder.available
modals.placeOrder.deliveryAddress
modals.placeOrder.deliveryPlaceholder
modals.placeOrder.failedOrder
modals.placeOrder.maxQuantityError
modals.placeOrder.maximum
modals.placeOrder.notes
modals.placeOrder.notesPlaceholder
modals.placeOrder.placeOrder
modals.placeOrder.placing
modals.placeOrder.quantity
modals.placeOrder.quantityPositive
modals.placeOrder.title
modals.placeOrder.total
nav.getStarted
nav.signIn
negotiation.aboveAverage
negotiation.acceptOffer
negotiation.asking
negotiation.belowAverage
negotiation.cashOnDelivery
negotiation.counter
negotiation.counterPrice
negotiation.credit
negotiation.dealConfirmed
negotiation.dealGap
negotiation.dealId
negotiation.dealMade
negotiation.declined
negotiation.deliveryDate
negotiation.earlyBonus
negotiation.earlyBonusRule
negotiation.escrow
negotiation.expired
negotiation.farmer
negotiation.farmerAsk
negotiation.flaggedOffers
negotiation.gap
negotiation.hours
negotiation.marketAvg
negotiation.marketBenchmark
negotiation.max
negotiation.maxRounds
negotiation.min
negotiation.minutes
negotiation.notes
negotiation.of
negotiation.offerDeclined
negotiation.offerHistory
negotiation.paymentTerms
negotiation.pricePerUnit
negotiation.quantity
negotiation.responding
negotiation.round
negotiation.roundsRemaining
negotiation.seconds
negotiation.sendCounter
negotiation.sending
negotiation.sessionClosed
negotiation.sessionExpired
negotiation.sessionRules
negotiation.source
negotiation.submitOffer
negotiation.submitOfferBtn
negotiation.submitting
negotiation.title
negotiation.todaysAvg
negotiation.trader
negotiation.veryClose
negotiation.viewOrder
negotiation.yourOffer
negotiation.yourOfferLabel
negotiation.yourOfferVsMarket
orderDetail.amount
orderDetail.backToOrders
orderDetail.buyer
orderDetail.buyerNotes
orderDetail.confirmTransaction
orderDetail.createTransaction
orderDetail.created
orderDetail.deliveryAddress
orderDetail.markComplete
orderDetail.noPermission
orderDetail.orderDetails
orderDetail.orderNotFound
orderDetail.paymentMethod
orderDetail.placedOn
orderDetail.product
orderDetail.seller
orderDetail.sellerNotes
orderDetail.status
orderDetail.totalAmount
orderDetail.transaction
orderDetail.transactionCreated
orderDetail.transactionFailed
orders.accept
orders.accepted
orders.allOrders
orders.allStatuses
orders.buyer
orders.cancel
orders.cancelled
orders.complete
orders.completed
orders.confirmStatus
orders.manageOrders
orders.myPurchases
orders.mySales
orders.noOrders
orders.noOrdersDesc
orders.orders
orders.pending
orders.reject
orders.rejected
orders.seller
orders.status
orders.thisOrder
orders.updateFailed
orders.view
orders.viewAs
productCard.farmer
productCard.message
productCard.order
productDetail.active
productDetail.available
productDetail.back
productDetail.contactFarmerFailed
productDetail.description
productDetail.farmer
productDetail.formalNegotiation
productDetail.goBack
productDetail.inactive
productDetail.loading
productDetail.messageFarmer
productDetail.noImage
productDetail.placeOrder
productDetail.productNotFound
productDetail.startNegotiationFailed
productDetail.starting
productDetail.totalValue
productDetail.unknown
productDetail.yourListing
profile.changePassword
profile.confirmNewPassword
profile.currentPassword
profile.editProfile
profile.location
profile.memberSince
profile.newPassword
profile.passwordChanged
profile.passwordMismatch
profile.phone
profile.profileUpdated
profile.saveChanges
profile.saving
review.comment
review.commentPlaceholder
review.deleteReview
review.leaveReview
review.multipleReviews
review.oneReview
review.rating
review.submitReview
review.submitting
review.title
role
trader.adjustFilters
trader.allCategories
trader.browseProducts
trader.clearFilters
trader.discoverProducts
trader.mostStock
trader.newest
trader.noProductsAvailable
trader.noProductsFound
trader.of
trader.priceHigh
trader.priceLow
trader.products
trader.searchProducts
trader.showing
upload.maxSize
upload.uploadFailed
upload.uploadImage
""".strip().split('\n')
used_keys = {k.strip() for k in used_keys_raw if k.strip()}

# Defined keys from translations.js (extracted manually from reading the file)
defined_keys_raw = """
nav.home
nav.browse
nav.myProducts
nav.orders
nav.messages
nav.negotiations
nav.signIn
nav.getStarted
nav.logout
nav.classify
common.loading
common.back
common.cancel
common.submit
common.save
common.delete
common.edit
common.view
common.search
common.filter
common.all
common.active
common.closed
common.waiting
common.yourTurn
common.noResults
auth.login
auth.register
auth.email
auth.password
auth.name
auth.phone
auth.location
auth.role
auth.farmer
auth.trader
auth.forgotPassword
auth.noAccount
auth.haveAccount
auth.welcomeBack
auth.signInSubtitle
auth.enterEmailPassword
auth.invalidResponse
auth.emailPlaceholder
auth.passwordPlaceholder
auth.signingIn
auth.createOne
auth.createAccount
auth.createAccountBtn
auth.joinCommunity
auth.fullName
auth.namePlaceholder
auth.passwordMinLength
auth.iAm
auth.sellProducts
auth.buyProducts
auth.creatingAccount
auth.fillAllFields
auth.passwordLengthError
auth.registrationFailed
auth.invalidEmailPassword
home.heroTitle
home.heroSubtitle
home.featuredProducts
home.categories
home.vegetables
home.fruits
home.grains
home.dairy
home.livestock
home.connectingFarmers
home.heroTitle2
home.heroFresh
home.heroDirect
home.description
home.goToDashboard
home.howItWorks
home.simplePlatform
home.forFarmers
home.forFarmersDesc
home.forTraders
home.forTradersDesc
home.directTrade
home.directTradeDesc
home.readyToStart
home.joinMarketplace
home.registerAsFarmer
home.registerAsTrader
home.marketplaceTagline
farmer.myProducts
farmer.manageListings
farmer.addProduct
farmer.addNewProduct
farmer.productTitle
farmer.pricePerUnitEGP
farmer.quantity
farmer.unit
farmer.category
farmer.selectCategory
farmer.description
farmer.descriptionPlaceholder
farmer.titlePlaceholder
farmer.pricePlaceholder
farmer.quantityPlaceholder
farmer.adding
farmer.yourListings
farmer.noProducts
farmer.noProductsDesc
farmer.failedLoad
farmer.fillRequired
farmer.priceQuantityPositive
farmer.createError
farmer.deleteConfirm
farmer.deleteFailed
farmer.total
farmer.totalProducts
farmer.activeListings
farmer.totalQuantity
farmer.totalValue
farmer.units
farmer.productCount
farmer.productCountPlural
trader.browseProducts
trader.discoverProducts
trader.searchProducts
trader.allCategories
trader.newest
trader.priceLow
trader.priceHigh
trader.mostStock
trader.showing
trader.of
trader.products
trader.clearFilters
trader.noProductsFound
trader.adjustFilters
trader.noProductsAvailable
productDetail.back
productDetail.noImage
productDetail.active
productDetail.inactive
productDetail.available
productDetail.totalValue
productDetail.description
productDetail.farmer
productDetail.unknown
productDetail.placeOrder
productDetail.formalNegotiation
productDetail.starting
productDetail.messageFarmer
productDetail.yourListing
productDetail.contactFarmerFailed
productDetail.startNegotiationFailed
productDetail.productNotFound
productDetail.goBack
orders.orders
orders.manageOrders
orders.viewAs
orders.allOrders
orders.myPurchases
orders.mySales
orders.status
orders.allStatuses
orders.pending
orders.accepted
orders.rejected
orders.completed
orders.cancelled
orders.noOrders
orders.noOrdersDesc
orders.seller
orders.buyer
orders.accept
orders.reject
orders.cancel
orders.complete
orders.confirmStatus
orders.thisOrder
orders.updateFailed
orderDetail.orderDetails
orderDetail.totalAmount
orderDetail.product
orderDetail.seller
orderDetail.buyer
orderDetail.deliveryAddress
orderDetail.buyerNotes
orderDetail.sellerNotes
orderDetail.transaction
orderDetail.status
orderDetail.paymentMethod
orderDetail.amount
orderDetail.created
orderDetail.markComplete
orderDetail.createTransaction
orderDetail.backToOrders
orderDetail.orderNotFound
orderDetail.noPermission
orderDetail.transactionCreated
orderDetail.transactionFailed
orderDetail.confirmTransaction
messages.messages
messages.conversations
messages.unread
messages.noConversations
messages.startChatting
messages.selectConversation
messages.selectConversationDesc
messages.noMessagesYet
messages.justNow
messages.startConversation
messages.re
messages.typeMessage
messages.failedSend
bananaClassifier.title
bananaClassifier.subtitle
bananaClassifier.dragDrop
bananaClassifier.dropHere
bananaClassifier.supports
bananaClassifier.removeImage
bananaClassifier.analyzeRipeness
bananaClassifier.analyzing
bananaClassifier.predictionResult
bananaClassifier.identifiedAs
bananaClassifier.confidence
bananaClassifier.overallGrade
bananaClassifier.gradeA
bananaClassifier.gradeC
bananaClassifier.topPredictions
bananaClassifier.classifyAnother
bananaClassifier.recentScans
bananaClassifier.confAbbr
bananaClassifier.failedClassify
modals.placeOrder.title
modals.placeOrder.quantity
modals.placeOrder.deliveryAddress
modals.placeOrder.deliveryAddressPlaceholder
modals.placeOrder.notes
modals.placeOrder.notesPlaceholder
modals.placeOrder.total
modals.placeOrder.perUnit
modals.placeOrder.available
modals.placeOrder.maxQuantity
modals.placeOrder.maxQuantityError
modals.placeOrder.quantityPositive
modals.placeOrder.placing
modals.placeOrder.placeOrderBtn
modals.placeOrder.failedOrder
modals.negotiatePrice.title
modals.negotiatePrice.yourOffer
modals.negotiatePrice.current
modals.negotiatePrice.quantity
modals.negotiatePrice.message
modals.negotiatePrice.messagePlaceholder
modals.negotiatePrice.originalTotal
modals.negotiatePrice.yourOfferLabel
modals.negotiatePrice.yourSavings
modals.negotiatePrice.belowAsking
modals.negotiatePrice.validPrice
modals.negotiatePrice.quantityRange
modals.negotiatePrice.sending
modals.negotiatePrice.sendOffer
modals.negotiatePrice.failedSend
modals.negotiatePrice.interested
productCard.message
productCard.order
productCard.viewAndOrder
productCard.messageFarmer
productCard.available
negotiation.title
negotiation.negotiations
negotiation.manageDeals
negotiation.startNegotiation
negotiation.noNegotiations
negotiation.dealConfirmed
negotiation.dealId
negotiation.earlyBonus
negotiation.viewOrder
negotiation.sessionClosed
negotiation.offerDeclined
negotiation.sessionExpired
negotiation.farmer
negotiation.trader
negotiation.asking
negotiation.round
negotiation.of
negotiation.roundsRemaining
negotiation.offerHistory
negotiation.submitOffer
negotiation.yourOffer
negotiation.pricePerUnit
negotiation.quantity
negotiation.deliveryDate
negotiation.paymentTerms
negotiation.notes
negotiation.cashOnDelivery
negotiation.credit
negotiation.escrow
negotiation.submitOfferBtn
negotiation.submitting
negotiation.responding
negotiation.acceptOffer
negotiation.counter
negotiation.reject
negotiation.sending
negotiation.sendCounter
negotiation.counterPrice
negotiation.marketBenchmark
negotiation.todaysAvg
negotiation.min
negotiation.max
negotiation.yourOfferVsMarket
negotiation.aboveAverage
negotiation.belowAverage
negotiation.source
negotiation.dealGap
negotiation.farmerAsk
negotiation.marketAvg
negotiation.yourOfferLabel
negotiation.gap
negotiation.veryClose
negotiation.sessionRules
negotiation.maxRounds
negotiation.earlyBonusRule
negotiation.flaggedOffers
negotiation.dealMade
negotiation.declined
negotiation.expired
negotiation.timeRemaining
negotiation.sessionExpires
negotiation.hours
negotiation.minutes
negotiation.seconds
negotiation.expiredLabel
admin.dashboard
admin.analytics
admin.users
admin.products
admin.orders
admin.negotiations
admin.totalUsers
admin.farmers
admin.traders
admin.totalProducts
admin.activeProducts
admin.delete
admin.edit
admin.view
admin.confirmDelete
admin.search
admin.status
admin.role
admin.actions
admin.noData
admin.logs
admin.recentOrders
admin.recentUsers
admin.pendingOrders
admin.completedOrders
admin.activeNegotiations
admin.totalNegotiations
admin.totalMessages
admin.unreadMessages
profile.title
profile.editProfile
profile.saveChanges
profile.cancel
profile.phone
profile.location
profile.avatar
profile.changeAvatar
profile.changePassword
profile.currentPassword
profile.newPassword
profile.confirmNewPassword
profile.passwordChanged
profile.profileUpdated
profile.passwordMismatch
profile.memberSince
review.title
review.leaveReview
review.yourReview
review.rating
review.comment
review.commentPlaceholder
review.submitReview
review.noReviews
review.noReviewsDesc
review.oneReview
review.multipleReviews
review.avgRating
review.deleteReview
review.reviewSubmitted
review.reviewDeleted
review.onlyCompleted
upload.uploadImage
upload.dragDrop
upload.clickToSelect
upload.maxSize
upload.uploading
upload.removeImage
upload.uploadFailed
""".strip().split('\n')
defined_keys = {k.strip() for k in defined_keys_raw if k.strip()}

# Compare
used_but_not_defined = used_keys - defined_keys
defined_but_not_used = defined_keys - used_keys

print("=== MISSING TRANSLATIONS (used in code but NOT defined in translations.js) ===\n")
for k in sorted(used_but_not_defined):
    print(k)

print(f"\n\n=== ORPHANED TRANSLATIONS (defined but NOT used in code) ===\n")
for k in sorted(defined_but_not_used):
    print(k)
